### ISSUE TITLE
Try sonar-branch-community plugin

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [lean-delivery/ansible-role-sonarqube#50]
##### SUMMARY
Try sonar-branch-community plugin
https://github.com/msanez/sonar-branch-community

##### ISSUE TYPE
 - Feature Idea

**Comment by dzmitry-rudnouski** [comment]
Pull request #54

**Comment by dzmitry-rudnouski** [comment]
Error with SonarQube 7.2.1:
`
java.lang.IllegalStateException: Fail to load plugin Branch Plugin Community Edition [branch]
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:81)
        at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:585)
        at org.sonar.server.platform.Platform.start(Platform.java:211)
        at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
        at org.sonar.server.platform.Platform.access$500(Platform.java:46)
        at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
        at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/sonar/server/branch/BranchFeatureExtension
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        at org.sonarsource.branch.BranchPlugin.define(BranchPlugin.java:24)
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:71)
        ... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.server.branch.BranchFeatureExtension
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        ... 24 common frames omitted
`

**Comment by dzmitry-rudnouski** [comment]
Fork: https://github.com/uknickwilliams/sonar-branch-community

**Comment by dzmitry-rudnouski** [comment]
The same exception for  https://github.com/uknickwilliams/sonar-branch-community/releases/download/2.0.5/branch-2.0.0.jar
